# Generated by Django 5.2.13 on 2026-04-22 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('tipo_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('ejecutivo_movil', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='FaseFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fase funnel',
                'verbose_name_plural': 'Fases funnel',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['cliente', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FunnelVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True)),
                ('lineas_nuevas', models.PositiveIntegerField(default=0)),
                ('lineas_portabilidad', models.PositiveIntegerField(default=0)),
                ('bam', models.PositiveIntegerField(default=0)),
                ('m2m', models.PositiveIntegerField(default=0)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel', to='core.cliente')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='core.fasefunnel')),
            ],
            options={
                'verbose_name': 'Funnel de venta',
                'verbose_name_plural': 'Funnel de ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineas_ponderadas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='core.funnelventa')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_gestion', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('contactado', 'Contactado'), ('no_contactado', 'No contactado'), ('interesado', 'Interesado'), ('seguimiento', 'Seguimiento'), ('descartado', 'Descartado')], max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='core.cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones', to='core.contactocliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión de llamada',
                'verbose_name_plural': 'Gestiones de llamadas',
                'ordering': ['-fecha_gestion'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_seguimiento', models.DateField()),
                ('proxima_accion', models.CharField(max_length=255)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.gestionllamada')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.CreateModel(
            name='CarteraAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Cartera asignada',
                'verbose_name_plural': 'Carteras asignadas',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'usuario', 'fecha_asignacion'), name='uq_cartera_cliente_usuario_fecha')],
            },
        ),
    ]
