# Generated by Django 6.0.3 on 2026-04-23 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=20)),
                ('lineas_portabilidad_vendidas', models.PositiveIntegerField(default=0)),
                ('lineas_nueva_vendidas', models.PositiveIntegerField(default=0)),
                ('lineas_m2m_vendidas', models.PositiveIntegerField(default=0)),
                ('monto_total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comision_calculada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonificacion_aplicada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='CALCULADA', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(choices=[('DECISOR', 'Decisor'), ('INFLUENCIADOR', 'Influenciador'), ('USUARIO', 'Usuario'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['cliente', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('EMAIL', 'Email'), ('REUNION', 'Reunión'), ('VIDEO', 'Video Llamada')], default='LLAMADA', max_length=20)),
                ('resultado', models.CharField(choices=[('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('SIN_RESPUESTA', 'Sin Respuesta'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('nota_ejecutiva', models.TextField(blank=True, null=True)),
                ('proximo_contacto_propuesto', models.DateField(blank=True, null=True)),
                ('productos_discutidos', models.CharField(blank=True, max_length=255, null=True)),
                ('accion_pendiente', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MetaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=20)),
                ('meta_lineas_portabilidad', models.PositiveIntegerField(default=0)),
                ('meta_lineas_nueva', models.PositiveIntegerField(default=0)),
                ('meta_lineas_m2m', models.PositiveIntegerField(default=0)),
                ('meta_monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comision_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_por_linea', models.DecimalField(decimal_places=2, max_digits=8)),
                ('factor_aceleracion', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('bonificacion_meta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Meta Ventas',
                'verbose_name_plural': 'Metas Ventas',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3)),
                ('etapa', models.CharField(choices=[('LEAD', 'Lead'), ('CONTACTO', 'Contacto Inicial'), ('CALIFICADO', 'Calificado'), ('PROPUESTA', 'Propuesta Presentada'), ('NEGOCIACION', 'Negociación'), ('CIERRE', 'Cierre Próximo'), ('GANADA', 'Venta Ganada'), ('PERDIDA', 'Venta Perdida'), ('DORMIDA', 'Dormida')], db_index=True, default='LEAD', max_length=20)),
                ('probabilidad', models.PositiveIntegerField(default=0)),
                ('productos', models.CharField(blank=True, max_length=255, null=True)),
                ('lineas', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_cierre_real', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('proximo_contacto', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comision_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], db_index=True, default='ABIERTA', max_length=10)),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='carteraasignada',
            name='uq_cartera_cliente_usuario_fecha',
        ),
        migrations.RemoveField(
            model_name='comisionventa',
            name='funnel',
        ),
        migrations.RemoveField(
            model_name='contactocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='gestionllamada',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='funnelventa',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='funnelventa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='gestionllamada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='gestionllamada',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='gestion',
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['-fecha_vencimiento', '-prioridad'], 'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='observacion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ejecutivo_movil',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='fecha_seguimiento',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='proxima_accion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DORMIDO', 'Dormido'), ('PROSPECT', 'Prospect')], db_index=True, default='PROSPECT', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='asignado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tipo',
            field=models.CharField(choices=[('ALERTA', 'Alerta'), ('RECORDATORIO', 'Recordatorio'), ('TAREA', 'Tarea'), ('NOTA', 'Nota')], default='RECORDATORIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado'], name='core_client_estado_c80503_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['usuario_asignado'], name='core_client_usuario_ad17a7_idx'),
        ),
        migrations.AddField(
            model_name='comision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='core.contacto'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comision',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metaventas'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='core.oportunidad'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='oportunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.oportunidad'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['estado'], name='core_seguim_estado_4e5f36_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['prioridad'], name='core_seguim_priorid_59577a_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['-fecha_vencimiento'], name='core_seguim_fecha_v_3e9181_idx'),
        ),
        migrations.RemoveField(
            model_name='carteraasignada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carteraasignada',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ComisionVenta',
        ),
        migrations.DeleteModel(
            name='ContactoCliente',
        ),
        migrations.DeleteModel(
            name='FaseFunnel',
        ),
        migrations.DeleteModel(
            name='FunnelVenta',
        ),
        migrations.DeleteModel(
            name='GestionLlamada',
        ),
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together={('cliente', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='metaventas',
            unique_together={('usuario', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('usuario', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['etapa'], name='core_oportu_etapa_59767e_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['usuario'], name='core_oportu_usuario_fdad60_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['estado'], name='core_oportu_estado_b8cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['-fecha_hora'], name='core_llamad_fecha_h_6412ba_idx'),
        ),
        migrations.DeleteModel(
            name='CarteraAsignada',
        ),
    ]
