# Generated by Django 5.2.13 on 2026-04-23 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comision_contacto_llamada_metaventas_oportunidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='metaventas',
            options={'verbose_name': 'Meta de Ventas', 'verbose_name_plural': 'Metas de Ventas'},
        ),
        migrations.RemoveIndex(
            model_name='llamada',
            name='core_llamad_fecha_h_6412ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='seguimiento',
            name='core_seguim_priorid_59577a_idx',
        ),
        migrations.RemoveIndex(
            model_name='seguimiento',
            name='core_seguim_fecha_v_3e9181_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Registro'),
        ),
        migrations.AddField(
            model_name='comision',
            name='fecha_calculo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cálculo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DORMIDO', 'Dormido'), ('PROSPECT', 'Prospect')], default='PROSPECT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo Asignado'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='bonificacion_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonificación Aplicada'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='comision_calculada',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Comisión Calculada'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='CALCULADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='lineas_m2m_vendidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Líneas M2M Vendidas'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='lineas_nueva_vendidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Líneas Nueva Vendidas'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='lineas_portabilidad_vendidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Líneas Portabilidad Vendidas'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='core.metaventas', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='monto_total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Total Vendido'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='periodo',
            field=models.CharField(max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total a Pagar'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='rol',
            field=models.CharField(choices=[('DECISOR', 'Decisor'), ('INFLUENCIADOR', 'Influenciador'), ('USUARIO', 'Usuario'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Móvil'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='accion_pendiente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acción Pendiente'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='core.contacto', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (min)'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='nota_ejecutiva',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='core.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='productos_discutidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Productos Discutidos'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='proximo_contacto_propuesto',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Contacto Propuesto'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='resultado',
            field=models.CharField(choices=[('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('SIN_RESPUESTA', 'Sin Respuesta'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='tipo',
            field=models.CharField(choices=[('LLAMADA', 'Llamada'), ('EMAIL', 'Email'), ('REUNION', 'Reunión'), ('VIDEO', 'Videollamada')], default='LLAMADA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='bonificacion_meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonificación Meta'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='comision_base',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Comisión Base'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='comision_por_linea',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Comisión por Línea'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='factor_aceleracion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Factor Aceleración'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='meta_lineas_m2m',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta Líneas M2M'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='meta_lineas_nueva',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta Líneas Nueva'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='meta_lineas_portabilidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta Líneas Portabilidad'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='meta_monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Meta Monto Total'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='periodo',
            field=models.CharField(max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='metaventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ventas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='comision_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comisión Estimada'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='ABIERTA', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='etapa',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('CONTACTO', 'Contacto Inicial'), ('CALIFICADO', 'Calificado'), ('PROPUESTA', 'Propuesta Presentada'), ('NEGOCIACION', 'Negociación'), ('CIERRE', 'Cierre Próximo'), ('GANADA', 'Venta Ganada'), ('PERDIDA', 'Venta Perdida'), ('DORMIDA', 'Dormida')], default='LEAD', max_length=20, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_cierre_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cierre Estimada'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_cierre_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cierre Real'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_ultimo_contacto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Contacto'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='lineas',
            field=models.PositiveIntegerField(default=0, verbose_name='Líneas'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='probabilidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Probabilidad (%)'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='productos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='proximo_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Contacto'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='asignado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado En'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='tipo',
            field=models.CharField(choices=[('ALERTA', 'Alerta'), ('RECORDATORIO', 'Recordatorio'), ('TAREA', 'Tarea'), ('NOTA', 'Nota')], default='RECORDATORIO', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['fecha_cierre_estimada'], name='core_oportu_fecha_c_8e34a0_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['fecha_vencimiento'], name='core_seguim_fecha_v_c86450_idx'),
        ),
    ]
