# Generated by Django 5.2.13 on 2026-05-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comision_options_alter_metaventas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llamada',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Gestión', 'verbose_name_plural': 'Gestiones'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='bam',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='BAM'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='edv',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ejecutivo de Ventas (EDV)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fijo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='¿Fijo?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fijo_movil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fijo+Móvil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='m2m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='M2M'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='movil',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='¿Móvil?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='q_total_lineas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Q Total Líneas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='renta_uf_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renta UF Total'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, choices=[('GRANDE', 'Grande'), ('CORP', 'Corporativo'), ('MED', 'Mediano'), ('PYM', 'PyME'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sub_movil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Móvil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='subgerencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subgerencia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='subrango',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subrango'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='voz',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='VOZ'),
        ),
    ]
