# Generated by Django 5.2.13 on 2026-05-14 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_creado_por_oportunidad_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('IMPORTADO', 'Importado (cartera)'), ('MANUAL', 'Prospectado por vendedor')], default='IMPORTADO', max_length=20, verbose_name='Origen'),
        ),
    ]
