# Generated by Django 5.2.15 on 2026-06-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_sub_movil_to_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUT')),
                ('dominio', models.CharField(blank=True, help_text='Ej: claro.cl — se usa para asignar usuarios automáticamente', max_length=100, null=True, unique=True, verbose_name='Dominio email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='q_total_lineas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Planes Multimedia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='voz',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='rol',
            field=models.CharField(choices=[('DECISOR', 'Decidor'), ('INFLUENCIADOR', 'Influenciador'), ('USUARIO', 'Usuario'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='core.contacto', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='core.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa', verbose_name='Empresa (tenant)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.empresa', verbose_name='Empresa (tenant)'),
        ),
    ]
