# Generated by Django 5.2.15 on 2026-06-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_empresa_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='core.empresa', verbose_name='Empresa (tenant)'),
        ),
        migrations.AddField(
            model_name='metaventas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_ventas', to='core.empresa', verbose_name='Empresa (tenant)'),
        ),
    ]
