# Generated by Django 5.2.15 on 2026-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_empresa_to_metaventas_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('PLATAFORMA', 'Plataforma (dueño del sistema)'), ('CLIENTE', 'Cliente (empresa contratante)')], default='CLIENTE', help_text='PLATAFORMA = dueño del sistema. Solo puede haber una.', max_length=20, verbose_name='Tipo de empresa'),
        ),
    ]
