# Generated by Django 5.2.15 on 2026-06-11 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_tipo_to_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena valores de campos personalizados definidos por la empresa (CampoPersonalizado)', null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena valores de campos personalizados definidos por la empresa (CampoPersonalizado)', null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena valores de campos personalizados definidos por la empresa (CampoPersonalizado)', null=True, verbose_name='Datos adicionales'),
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidad', models.CharField(choices=[('CLIENTE', 'Cliente'), ('OPORTUNIDAD', 'Oportunidad'), ('SEGUIMIENTO', 'Seguimiento')], help_text='Modelo al que pertenece este campo', max_length=20, verbose_name='Entidad')),
                ('nombre', models.CharField(help_text='Ej: "Número de Licencias"', max_length=100, verbose_name='Nombre visible')),
                ('clave', models.SlugField(help_text='Identificador único en JSON. Solo letras, números y guiones bajos. Ej: num_licencias', max_length=100, verbose_name='Clave interna')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('DATE', 'Fecha'), ('SELECT', 'Lista desplegable'), ('BOOL', 'Booleano (Sí/No)')], default='TEXT', max_length=10, verbose_name='Tipo de campo')),
                ('opciones', models.JSONField(blank=True, help_text='Solo para tipo Lista. Formato: ["Opción A", "Opción B"]', null=True, verbose_name='Opciones')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
                'ordering': ['empresa', 'entidad', 'orden', 'nombre'],
                'unique_together': {('empresa', 'entidad', 'clave')},
            },
        ),
    ]
