# Generated by Django 5.2.13 on 2026-06-11 02:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_campo_personalizado_datos_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('empresa', 'usuario', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='metaventas',
            unique_together={('empresa', 'usuario', 'periodo')},
        ),
    ]
