# Generated by Django 5.2.15 on 2026-06-13 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_unique_together_metaventas_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoMensualSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=7, verbose_name='Periodo (YYYY-MM)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EXPORTADO', 'Exportado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha generación')),
                ('total_socios', models.PositiveIntegerField(default=0, verbose_name='Total socios')),
                ('total_monto', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total monto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
            ],
            options={
                'verbose_name': 'Consolidado Mensual Sindicato',
                'verbose_name_plural': 'Consolidados Mensuales Sindicato',
            },
        ),
        migrations.CreateModel(
            name='SocioSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('estado_laboral', models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA_MEDICA', 'Licencia médica'), ('DESVINCULADO', 'Desvinculado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado laboral')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha ingreso')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
            ],
            options={
                'verbose_name': 'Socio Sindicato',
                'verbose_name_plural': 'Socios Sindicato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficioSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('orden_export', models.PositiveSmallIntegerField(default=100, verbose_name='Orden exportación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_beneficio_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
            ],
            options={
                'verbose_name': 'Tipo Beneficio Sindicato',
                'verbose_name_plural': 'Tipos Beneficio Sindicato',
                'ordering': ['orden_export', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=7, verbose_name='Periodo (YYYY-MM)')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('referencia_externa', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia externa')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_sindicato_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.sociosindicato', verbose_name='Socio')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.tipobeneficiosindicato', verbose_name='Tipo beneficio')),
            ],
            options={
                'verbose_name': 'Movimiento Sindicato',
                'verbose_name_plural': 'Movimientos Sindicato',
                'ordering': ['-periodo', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoDetalleSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_aprobado', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto aprobado')),
                ('motivo_ajuste', models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo ajuste')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidado_detalles_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
                ('consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.consolidadomensualsindicato', verbose_name='Consolidado')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidado_detalles', to='core.sociosindicato')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidado_detalles', to='core.tipobeneficiosindicato')),
            ],
            options={
                'verbose_name': 'Consolidado Detalle Sindicato',
                'verbose_name_plural': 'Consolidado Detalles Sindicato',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=40, verbose_name='Acción')),
                ('entidad', models.CharField(max_length=60, verbose_name='Entidad')),
                ('entidad_id', models.CharField(max_length=40, verbose_name='ID entidad')),
                ('periodo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Periodo')),
                ('resumen', models.CharField(max_length=255, verbose_name='Resumen')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP origen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_sindicato', to='core.empresa', verbose_name='Empresa (tenant)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_sindicato', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría Sindicato',
                'verbose_name_plural': 'Auditorías Sindicato',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'created_at'], name='core_audito_empresa_6c5d02_idx'), models.Index(fields=['empresa', 'entidad', 'entidad_id'], name='core_audito_empresa_7f92b2_idx'), models.Index(fields=['empresa', 'periodo'], name='core_audito_empresa_dd6b9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consolidadomensualsindicato',
            index=models.Index(fields=['empresa', 'estado'], name='core_consol_empresa_1c6a54_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidadomensualsindicato',
            index=models.Index(fields=['empresa', 'periodo'], name='core_consol_empresa_ea9cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolidadomensualsindicato',
            constraint=models.UniqueConstraint(fields=('empresa', 'periodo'), name='uniq_cons_mensual_sind_empresa_periodo'),
        ),
        migrations.AddConstraint(
            model_name='consolidadomensualsindicato',
            constraint=models.CheckConstraint(condition=models.Q(('total_monto__gte', 0)), name='chk_cons_sind_total_monto_nonneg'),
        ),
        migrations.AddIndex(
            model_name='sociosindicato',
            index=models.Index(fields=['empresa', 'rut'], name='core_socios_empresa_50cdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='sociosindicato',
            index=models.Index(fields=['empresa', 'estado'], name='core_socios_empresa_963ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='sociosindicato',
            index=models.Index(fields=['empresa', 'estado_laboral'], name='core_socios_empresa_dade5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sociosindicato',
            constraint=models.UniqueConstraint(fields=('empresa', 'rut'), name='uniq_socio_sindicato_empresa_rut'),
        ),
        migrations.AddIndex(
            model_name='tipobeneficiosindicato',
            index=models.Index(fields=['empresa', 'estado'], name='core_tipobe_empresa_9f6b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='tipobeneficiosindicato',
            index=models.Index(fields=['empresa', 'orden_export'], name='core_tipobe_empresa_d84b5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipobeneficiosindicato',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_tipo_benef_sind_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tipobeneficiosindicato',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_tipo_benef_sind_empresa_nombre'),
        ),
        migrations.AddIndex(
            model_name='movimientosindicato',
            index=models.Index(fields=['empresa', 'periodo'], name='core_movimi_empresa_a0d6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosindicato',
            index=models.Index(fields=['empresa', 'estado'], name='core_movimi_empresa_32f1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosindicato',
            index=models.Index(fields=['empresa', 'socio', 'periodo'], name='core_movimi_empresa_a3eba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientosindicato',
            constraint=models.UniqueConstraint(fields=('empresa', 'socio', 'tipo_beneficio', 'periodo', 'referencia_externa'), name='uniq_mov_sind_empresa_socio_benef_periodo_ref'),
        ),
        migrations.AddConstraint(
            model_name='movimientosindicato',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_mov_sind_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='consolidadodetallesindicato',
            index=models.Index(fields=['consolidado', 'socio'], name='core_consol_consoli_fd4485_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidadodetallesindicato',
            index=models.Index(fields=['consolidado', 'tipo_beneficio'], name='core_consol_consoli_d2d3c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolidadodetallesindicato',
            constraint=models.UniqueConstraint(fields=('consolidado', 'socio', 'tipo_beneficio'), name='uniq_cons_det_sind_consolidado_socio_benef'),
        ),
        migrations.AddConstraint(
            model_name='consolidadodetallesindicato',
            constraint=models.CheckConstraint(condition=models.Q(('monto_aprobado__gte', 0)), name='chk_cons_det_sind_monto_nonneg'),
        ),
    ]
