# Generated by Django 5.2.15 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_consolidadomensualsindicato_sociosindicato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosindicato',
            name='fuente',
            field=models.CharField(
                choices=[('GAS', 'Gas'), ('TELEFONIA', 'Telefonia'), ('COPEUCH', 'Copeuch')],
                default='GAS',
                max_length=20,
                verbose_name='Fuente',
            ),
        ),
        migrations.AddField(
            model_name='movimientosindicato',
            name='metadata_fuente',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata fuente'),
        ),
    ]
