# Generated by Django 5.2.15 on 2026-06-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alertas_sindicato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='sindicato/documentos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre archivo')),
                ('tipo_archivo', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PNG', 'PNG')], max_length=5, verbose_name='Tipo archivo')),
                ('estado', models.CharField(choices=[('SUBIDO', 'Subido'), ('PROCESADO', 'Procesado'), ('EN_REVISION', 'En revisión'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='SUBIDO', max_length=15, verbose_name='Estado')),
                ('texto_extraido', models.TextField(blank=True, default='', verbose_name='Texto extraído')),
                ('datos_extraidos', models.JSONField(blank=True, default=dict, verbose_name='Datos extraídos')),
                ('error_mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('observacion_revision', models.TextField(blank=True, default='', verbose_name='Observación revisión')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha revisión')),
            ],
            options={
                'verbose_name': 'Documento Sindicato',
                'verbose_name_plural': 'Documentos Sindicato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='alertasindicato',
            new_name='core_alerta_empresa_87685f_idx',
            old_name='core_alerta_empresa_aaf1ec_idx',
        ),
        migrations.RenameIndex(
            model_name='alertasindicato',
            new_name='core_alerta_empresa_223b0d_idx',
            old_name='core_alerta_empresa_9f5f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='alertasindicato',
            new_name='core_alerta_empresa_f300f9_idx',
            old_name='core_alerta_empresa_4d0ec7_idx',
        ),
        migrations.RenameIndex(
            model_name='alertasindicato',
            new_name='core_alerta_empresa_8896f4_idx',
            old_name='core_alerta_empresa_843d83_idx',
        ),
        migrations.RenameIndex(
            model_name='alertasindicato',
            new_name='core_alerta_empresa_6a95bb_idx',
            old_name='core_alerta_empresa_4f8214_idx',
        ),
        migrations.AlterField(
            model_name='movimientosindicato',
            name='fuente',
            field=models.CharField(choices=[('GAS', 'Gas'), ('TELEFONIA', 'Telefonia'), ('COPEUCH', 'Copeuch'), ('DOCUMENTO', 'Documento OCR')], default='GAS', max_length=20, verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='documentosindicato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sindicato', to='core.empresa', verbose_name='Empresa (tenant)'),
        ),
        migrations.AddField(
            model_name='documentosindicato',
            name='movimiento_creado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_origen', to='core.movimientosindicato', verbose_name='Movimiento creado'),
        ),
        migrations.AddField(
            model_name='documentosindicato',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_sindicato_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='documentosindicato',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_sindicato_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='documentosindicato',
            index=models.Index(fields=['empresa', 'estado'], name='core_docume_empresa_132130_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosindicato',
            index=models.Index(fields=['empresa', 'created_at'], name='core_docume_empresa_77510f_idx'),
        ),
    ]
