# Generated by Django 5.2.15 on 2026-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_documentosindicato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosindicato',
            name='fuente',
            field=models.CharField(choices=[('GAS', 'Gas'), ('TELEFONIA', 'Telefonía'), ('COPEUCH', 'Copeuch'), ('DOCUMENTO', 'Documento OCR'), ('VETERINARIA', 'Veterinaria'), ('GIMNASIO', 'Gimnasio'), ('HAPPYLAND', 'Happyland'), ('DEUDA_SINDICAL', 'Deuda Sindical'), ('CUOTA_EXTRAORDINARIA', 'Cuota Extraordinaria'), ('DESCUENTO_DHL', 'Descuento DHL'), ('CLINICA_OMI', 'Clínica OMI'), ('GENERICA', 'Genérica')], default='GAS', max_length=20, verbose_name='Fuente'),
        ),
    ]
